export var allRoleEN = [
  {
    head: 'Halabja Group',
    role_value: 'group:',
    indeterminate: false,
    allChecked: false,
    counter: 0,
    options: [
      { label: 'Read', value: 'read', checked: false },
      { label: 'Plan', value: 'plan', checked: false },
      { label: 'IT', value: 'it', checked: false },
      { label: 'HR', value: 'hr', checked: false },
      { label: 'PMO', value: 'pmo', checked: false },
      { label: 'Properties', value: 'property', checked: false },
      { label: 'Accounting and control', value: 'accounting-and-control', checked: false },
      { label: 'Legal', value: 'legal', checked: false },
      { label: 'Administration', value: 'administration', checked: false },
      { label: 'Finance', value: 'finance', checked: false },
      { label: 'Supplychain', value: 'supplychain', checked: false },
      { label: 'Commercial', value: 'commercial', checked: false },
      { label: 'Machines', value: 'machines', checked: false },
      { label: 'Reporting & analysis', value: 'reporting', checked: false },
      { label: 'Safety', value: 'safety', checked: false },
      { label: 'Landscape', value: 'landscape', checked: false },
      { label: 'Accounting and control', value: 'accounting-control', checked: false },
    ],
  },
  {
    head: 'Halabja Concrete',
    role_value: 'hcnt:',
    indeterminate: false,
    allChecked: false,
    counter: 0,
    options: [
      { label: 'Read', value: 'read', checked: false },
      { label: 'Sales per month', value: 'sales-per-month', checked: false },
      { label: 'Sales per date', value: 'sales-per-date', checked: false },
      { label: 'Sales per customer', value: 'sales-per-customer', checked: false },
      { label: 'Sales per product type', value: 'sales-per-product-type', checked: false },
    ],
  },
  {
    head: 'Aran Asphalt',
    role_value: 'aran:',
    indeterminate: false,
    allChecked: false,
    counter: 0,
    options: [
      { label: 'Read', value: 'read', checked: false },
    ],
  },
  {
    head: 'Halabja Petrol Station',
    role_value: 'hps:',
    indeterminate: false,
    allChecked: false,
    counter: 0,
    options: [
      { label: 'Read', value: 'read', checked: false },
    ],
  },
  {
    head: 'Halabja Cleaning Service',
    role_value: 'hcs:',
    indeterminate: false,
    allChecked: false,
    counter: 0,
    options: [
      { label: 'Read', value: 'read', checked: false },
    ],
  },
  {
    head: 'Halabja Telecom Services',
    role_value: 'hts:',
    indeterminate: false,
    allChecked: false,
    counter: 0,
    options: [
      { label: 'Read', value: 'read', checked: false },
    ],
  },
  {
    head: 'Family mall',
    role_value: 'fm:',
    indeterminate: false,
    allChecked: false,
    counter: 0,
    options: [
      { label: 'Read', value: 'read', checked: false },
      { label: 'Pax Gym', value: 'pax-gym', checked: false },
      { label: 'Poney', value: 'poney', checked: false },
    ],
  },
  {
    head: 'Hilal Brick Factory',
    role_value: 'hbf:',
    indeterminate: false,
    allChecked: false,
    counter: 0,
    options: [
      { label: 'Read', value: 'read', checked: false },
      { label: 'Sales per month', value: 'sales-per-month', checked: false },
      { label: 'Sales per gov', value: 'sales-per-gov', checked: false },
      { label: 'Sales per customer', value: 'sales-per-customer', checked: false },
      { label: 'Sales per brick type', value: 'sales-per-brick-type', checked: false },
      { label: 'Inventory', value: 'inventory-now', checked: false },
      { label: 'Inventory and sold per date', value: 'inventory-and-sold-per-date', checked: false },
    ],
  },
  {
    head: 'Aso Brick Factory',
    role_value: 'abf:',
    indeterminate: false,
    allChecked: false,
    counter: 0,
    options: [
      { label: 'Read', value: 'read', checked: false },
      { label: 'Sales per month', value: 'sales-per-month', checked: false },
      { label: 'Sales per gov', value: 'sales-per-gov', checked: false },
      { label: 'Sales per customer', value: 'sales-per-customer', checked: false },
      { label: 'Sales per brick type', value: 'sales-per-brick-type', checked: false },
      { label: 'Inventory', value: 'inventory-now', checked: false },
      { label: 'Inventory and sold per date', value: 'inventory-and-sold-per-date', checked: false },
    ],
  },
  {
    head: 'Ishtar Brick Factory',
    role_value: 'ibf:',
    indeterminate: false,
    allChecked: false,
    counter: 0,
    options: [
      { label: 'Read', value: 'read', checked: false },
    ],
  },
  {
    head: 'Halabja Trading',
    role_value: 'ht:',
    indeterminate: false,
    allChecked: false,
    counter: 0,
    options: [
      { label: 'Read', value: 'read', checked: false },
    ],
  },
  {
    head: 'Rasan Farm',
    role_value: 'rasan-farm:',
    indeterminate: false,
    allChecked: false,
    counter: 0,
    options: [
      { label: 'Read', value: 'read', checked: false },
    ],
  },
  {
    head: 'Rasan Olive Oil',
    role_value: 'rasan-olive:',
    indeterminate: false,
    allChecked: false,
    counter: 0,
    options: [
      { label: 'Read', value: 'read', checked: false },
    ],
  },
  {
    head: 'Halabja Contracting',
    role_value: 'h-contracting:',
    indeterminate: false,
    allChecked: false,
    counter: 0,
    options: [
      { label: 'Read', value: 'read', checked: false },
    ],
  },
  {
    head: 'Garden City',
    role_value: 'gc:',
    indeterminate: false,
    allChecked: false,
    counter: 0,
    options: [
      { label: 'Read', value: 'read', checked: false },
    ],
  },
   {
    head: 'Users',
    role_value: 'user:',
    indeterminate: false,
    allChecked: false,
    counter: 0,
    options: [
      { label: 'Read', value: 'read', checked: false },
      { label: 'Add', value: 'add', checked: false },
      { label: 'Update', value: 'update', checked: false },
      { label: 'Delete', value: 'delete', checked: false },
    ],
  },

  {
    head: 'Roles',
    role_value: 'role:',
    indeterminate: false,
    allChecked: false,
    counter: 0,
    options: [
      { label: 'Read', value: 'read', checked: false },
      { label: 'Add', value: 'add', checked: false },
      { label: 'Update', value: 'update', checked: false },
      { label: 'Delete', value: 'delete', checked: false },
    ],
  },
  {
    head: 'Settings',
    role_value: 'setting:',
    indeterminate: false,
    allChecked: false,
    counter: 0,
    options: [
      { label: 'Read', value: 'read', checked: false },
      { label: 'Add', value: 'add', checked: false },
      { label: 'Update', value: 'update', checked: false },
      { label: 'Delete', value: 'delete', checked: false },
    ],
  },
  {
    head: 'Log',
    role_value: 'log:',
    indeterminate: false,
    allChecked: false,
    counter: 0,
    options: [
      { label: 'Read', value: 'read', checked: false },
    ],
  },
  

];



